Added `full_case` and `parallel_case` attributes
zachjs/sv2v pull request #274
Opened 2024-01-23 02:52 UTC by sifferman

Fixes https://github.com/zachjs/sv2v/issues/270.

I am happy to make changes as needed!

2024-01-29 03:13 UTC, zachjs requested changes
Thank you very much for your contribution! I'm interested in getting this change merged. I'm happy to make any of the requested changes myself if you do not have time to do so, especially for minor nits.

2024-01-29 03:13 UTC, zachjs commented on test/relong/case.v
>          // Unique keyword doesn't exist in Verilog
I'd prefer not to change tests in this suite. These changes aren't necessary for these tests to pass, I think.

2024-01-29 03:13 UTC, zachjs commented on test/core/case_violation_checks.sv
> +    initial ;
Minor nit: I'd prefer no-ops like this and some of the extra whitespace be removed to better match the other tests.

2024-01-29 03:13 UTC, zachjs commented on test/core/case_violation_checks.v
> +module top;
I prefer to produce the reference conversion "by hand" for stylistic purposes and to double-check the results.

The testing setup mostly looks at the behavior of each version (see the test readme). I think this test would pass without your changes, so we'll at least want add a `.pat` file checking that the attributes are being used.

2024-01-29 03:13 UTC, zachjs commented on src/Convert/Unique.hs
>  convertStmt :: Stmt -> Stmt
Minor: At the top of this file, the description of the conversion is now out of date.
Minor: The changelog could be updated, too, but I can take care of this later.

2024-01-29 04:30 UTC, sifferman commented on test/core/case_violation_checks.sv
> +    initial ;
I had to add a no-op initial block or else the test would fail. Is that fine?

2024-01-29 04:42 UTC, sifferman commented on src/Convert/Unique.hs
> +    convertStmt (Case Unique kw expr cases)
That's very interesting! Actually, I do believe that Yosys is more correct here. I was going off <https://docs.xilinx.com/r/en-US/ug901-vivado-synthesis/Case-Statement>. I'll make that change

2024-01-29 18:58 UTC, sifferman commented on src/Convert/Unique.hs
> +    convertStmt (Case Unique kw expr cases)
I just checked DC and Genus, and I couldn't find any mention of applying full_case/parallel_case to priority/unique.

2024-02-24 09:11 UTC, sifferman commented
@zachjs Any tips on this? I'd like to have this feature merged soon 😃

2024-02-25 18:43 UTC, zachjs commented
Sure! Can you explain why we also add the `synthesis` attributed? I'll also make some minor tweaks locally.

2024-02-25 18:49 UTC, sifferman commented
> Can you explain why we also add the `synthesis` attributed?

From IEC 62142:2005 Section 6.1:

> If a synthesis tool supports pragmas to control the structure of the synthesized netlist or to give direction to the synthesis tool, attributes shall be used to convey the required information. The first attribute within the attribute instance shall be synthesis followed by a comma separated list of synthesis-related attributes. Here is the template for specifying such an attribute.
> ```
> (* synthesis, <attribute=value_or_optional_value>
>               { , <attribute=value_or_optional_value> } *)
> ```
> The attribute synthesis shall be listed as the first attribute in an attribute instance.
> 
> NOTE -- By placing the synthesis attribute first, a synthesis tool can more easily parse the attribute instance to determine if the rest of the attributes in the attribute instance are intended for the synthesis tool or for a different to

I'm not certain if tools actually require/recognize this though.

2024-02-25 18:59 UTC, zachjs commented
I'm confident that Yosys doesn't care about that attribute. Can you check the downstream tools you're using?

2024-02-25 20:13 UTC, sifferman commented
I just ran the following example on Vivado v2019.1, Genus 20.11-s111_1, and DC R-2020.09-SP4:

```verilog
module case_test (int2, int1, int0, irq);
    output int2, int1, int0;
    input [2:0] irq;
    reg int2, int1, int0;

    always @(irq) begin
        {int2, int1, int0} = 3'b0;
        (* parallel_case *)
        casez (irq)
            3'b1??: int2 = 1'b1;
            3'b?1?: int1 = 1'b1;
            3'b??1: int0 = 1'b1;
        endcase
    end
endmodule
```

Like Yosys, Vivado and Genus are fine leaving off `synthesis`, (but also work properly if included).

Interestingly, as far as I see, DC does not accept `full_case`/`parallel_case` from an attribute at all. It only accepts it as a directive from a comment:
```verilog
        casez (irq) // synopsys parallel_case
            3'b1??: int2 = 1'b1;
            3'b?1?: int1 = 1'b1;
            3'b??1: int0 = 1'b1;
        endcase
```

2024-02-25 21:08 UTC, zachjs commented on test/core/case_violation_checks.sv
> +    initial ;
The tests pass for me without the initial block. I'll push that version up.

2024-02-25 21:09 UTC, zachjs commented
Based on those results, I'll drop the `synthesis` attribute. Thanks!

2024-03-11 03:44 UTC, zachjs approved these changes
Thank you very much for your contribution (and patience)!

2024-03-11 03:45 UTC, merged

2024-03-11 17:52 UTC, sifferman commented
Thanks so much!